### ISSUE TITLE
.c / .check double 20 bug

### ISSUE THREAD

**Issue by Obstkuchen3000** [rngShard/dsa-discord-bot#11]
When rolling a double 20 the remaining points are shown as the maximum

<Janus Bohm> Checking Athletik ['GE', 'KO', 'KK']=[12, 11, 11] (7) +0:
(info) BE-relevant skill, difficulty adjusted for BE=0 & eBE=x2, +0 >> +0
Rolling [15, 20, 20] >> Epic failure ...
Result = +7

**Comment by rescuehero** [comment]
simply change:
Rolling [15, 20, 20] >> Epic failure ...
Result = +7

to:
Rolling [15, 20, 20]
Result = +7 >> Epic failure ...

?

**Comment by rescuehero** [comment]
pushed my suggestion into develop-branch as own commit (easyfix?)

**Comment by rescuehero** [comment]
solution provided at #6 


quote:
![image](https://user-images.githubusercontent.com/11653204/80959121-6e516f00-8e06-11ea-9aba-5b2934b5087b.png)


comment/info only shows at BE-relevant skills

fail/sucess due to 2x20/2x1 is shown directly at the bottom line, which should lead to less missunderstandings

**Comment by rescuehero** [comment]
@rngShard  which one do you like most?
above pic with the result+explanation inline (already implemented) 
or 
simply suppressing the result-line (merged by you into master)?

I like your implementation with the simple switch by using an if <3 --> easy change of  style possible
