### ISSUE TITLE
Den Output abspecken!

### ISSUE THREAD

**Issue by ZsadistWoW** [rngShard/dsa-discord-bot#6]
Hallo lieber Entwickler-Gott!
Wie wäre es, wenn man den output entweder abspeckt oder einen abgespeckten output über einen gesonderten Befehl ermöglicht?
Momentan ist es ja noch:

< Loranin Banjenko > Checking selbstbeherrschung ['MU', 'KO', 'KK']=[15, 13, 10] (8) +0:
Rolling [14, 19, 2] >> Success!
Result = +2

Wie wäre es stattdessen mit etwas wie:

**< Loranin Banjenko > Checking selbstbeherrschung +0:
Rolling [14, 19, 2] >> +2**

Oder 

**< Loranin Banjenko > Checking selbstbeherrschung +0:
14, 19, 2 >> +2**

Oder

**< Loranin Banjenko > Probe auf: selbstbeherrschung (+0): 14, 19, 2 >> +2**

dankeschön - Kuss auf die Eichel
Dein Maximus

**Comment by rescuehero** [comment]
suggestion: different output config - global variables

i like it the way it is :D

**Comment by rescuehero** [comment]
added embeds for cleaner outputs - maybe it fulfills all requirements

quote:
![image](https://user-images.githubusercontent.com/11653204/80959121-6e516f00-8e06-11ea-9aba-5b2934b5087b.png)

comment/info only shows at BE-relevant skills

fail/sucess due to 2x20/2x1 is shown directly at the bottom line, which should lead to less missunderstandings
